# Generated by Django 6.0.8 on 2026-08-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
