# Generated by Django 6.0.8 on 2026-08-05 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references')], max_length=8)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField(help_text='Requested clip length, in seconds.')),
                ('estimated_render_seconds', models.PositiveIntegerField(help_text='Expected wall-clock render time for this combination.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['mode', 'width', 'height', 'duration_seconds'],
            },
        ),
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references')], max_length=8)),
                ('raw_prompt', models.TextField()),
                ('improved_prompt', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('estimated_seconds', models.PositiveIntegerField(help_text='Snapshot of preset.estimated_render_seconds at queue time.')),
                ('q_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('comfyui_prompt_id', models.CharField(blank=True, default='', max_length=64)),
                ('video_file', models.FileField(blank=True, upload_to='generated_videos/%Y/%m/')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to=settings.AUTH_USER_MODEL)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='generation.renderpreset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='references/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='generation.generationjob')),
            ],
            options={
                'ordering': ['kind', 'order'],
            },
        ),
    ]
