# Generated by Django 6.0.8 on 2026-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renderpreset',
            options={'ordering': ['mode', 'is_draft', 'width', 'height', 'duration_seconds']},
        ),
        migrations.AddField(
            model_name='renderpreset',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Fast/low-quality preset meant for previewing a prompt, not a final render.'),
        ),
        migrations.AddField(
            model_name='renderpreset',
            name='steps',
            field=models.PositiveIntegerField(default=20, help_text='Sampler steps (BasicScheduler.steps).'),
        ),
    ]
