# Generated by Django 6.0.8 on 2026-08-05 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0003_seed_render_presets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references')], max_length=8)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('duration_seconds', models.FloatField()),
                ('steps', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ok', 'OK'), ('oom_error', 'OOM / execution error'), ('timeout', 'Timed out'), ('crashed', 'ComfyUI unreachable (crashed)')], max_length=16)),
                ('render_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('comfyui_prompt_id', models.CharField(blank=True, default='', max_length=64)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['mode', 'width', 'height', 'duration_seconds'],
                'constraints': [models.UniqueConstraint(fields=('mode', 'width', 'height', 'duration_seconds', 'steps'), name='unique_benchmark_combo')],
            },
        ),
        migrations.CreateModel(
            name='PromptChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resulting_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='generation.generationjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='generation.promptchatsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
