# Generated by Django 6.0.8 on 2026-08-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0004_benchmarkresult_promptchatsession_promptchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done')], default='queued', max_length=16),
        ),
    ]
