# Generated by Django 6.0.8 on 2026-08-05 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0005_alter_generationjob_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renderpreset',
            options={'ordering': ['mode', 'megapixels']},
        ),
        migrations.RemoveField(
            model_name='renderpreset',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='renderpreset',
            name='estimated_render_seconds',
        ),
        migrations.RemoveField(
            model_name='renderpreset',
            name='height',
        ),
        migrations.RemoveField(
            model_name='renderpreset',
            name='width',
        ),
        migrations.AddField(
            model_name='generationjob',
            name='aspect_ratio',
            field=models.CharField(default='16:9', help_text='e.g. "16:9" -- see resolution.ASPECT_RATIOS.', max_length=8),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='duration_seconds',
            field=models.FloatField(default=5.0, help_text='Snapshot of duration.duration_seconds at queue time.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='height',
            field=models.PositiveIntegerField(default=768, help_text='Computed from megapixels + aspect_ratio at queue time.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='megapixels',
            field=models.FloatField(default=1.0, help_text='Snapshot of preset.megapixels at queue time.'),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='width',
            field=models.PositiveIntegerField(default=1344, help_text='Computed from megapixels + aspect_ratio at queue time.'),
        ),
        migrations.AddField(
            model_name='renderpreset',
            name='label',
            field=models.CharField(default='', help_text='e.g. "Draft", "Standard", "High quality".', max_length=60),
        ),
        migrations.AddField(
            model_name='renderpreset',
            name='megapixels',
            field=models.FloatField(default=1.0, help_text='Target pixel count for this tier, in megapixels.'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='estimated_seconds',
            field=models.PositiveIntegerField(help_text='Snapshot of duration.estimated_render_seconds at queue time.'),
        ),
        migrations.CreateModel(
            name='RenderDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.FloatField(help_text='Requested clip length, in seconds.')),
                ('estimated_render_seconds', models.PositiveIntegerField(help_text='Expected wall-clock render time for this (preset, duration) combination.')),
                ('is_active', models.BooleanField(default=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='generation.renderpreset')),
            ],
            options={
                'ordering': ['preset', 'duration_seconds'],
            },
        ),
        migrations.AddField(
            model_name='generationjob',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='generation.renderduration'),
        ),
        migrations.AddConstraint(
            model_name='renderduration',
            constraint=models.UniqueConstraint(fields=('preset', 'duration_seconds'), name='unique_preset_duration'),
        ),
    ]
