# Generated by Django 6.0.8 on 2026-08-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0007_delete_jobs_without_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='aspect_ratio',
            field=models.CharField(help_text='e.g. "16:9" -- see resolution.ASPECT_RATIOS.', max_length=8),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='generation.renderduration'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='duration_seconds',
            field=models.FloatField(help_text='Snapshot of duration.duration_seconds at queue time.'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='height',
            field=models.PositiveIntegerField(help_text='Computed from megapixels + aspect_ratio at queue time.'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='megapixels',
            field=models.FloatField(help_text='Snapshot of preset.megapixels at queue time.'),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='width',
            field=models.PositiveIntegerField(help_text='Computed from megapixels + aspect_ratio at queue time.'),
        ),
        migrations.AlterField(
            model_name='renderpreset',
            name='label',
            field=models.CharField(help_text='e.g. "Draft", "Standard", "High quality".', max_length=60),
        ),
        migrations.AlterField(
            model_name='renderpreset',
            name='megapixels',
            field=models.FloatField(help_text='Target pixel count for this tier, in megapixels.'),
        ),
    ]
