# Generated by Django 6.0.8 on 2026-08-05 22:12

import generation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0010_narrow_megapixel_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='video_file',
            field=models.FileField(blank=True, upload_to=generation.models.generated_video_upload_path),
        ),
        migrations.AlterField(
            model_name='referenceasset',
            name='file',
            field=models.FileField(upload_to=generation.models.reference_upload_path),
        ),
    ]
