# Generated by Django 6.0.8 on 2026-08-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0016_generationjob_phase_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarkresult',
            name='mode',
            field=models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references'), ('t2i', 'Image from text'), ('r2i', 'Provide references'), ('t2a', 'Audio from text'), ('r2a', 'Provide references')], max_length=8),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='mode',
            field=models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references'), ('t2i', 'Image from text'), ('r2i', 'Provide references'), ('t2a', 'Audio from text'), ('r2a', 'Provide references')], max_length=8),
        ),
        migrations.AlterField(
            model_name='promptchatsession',
            name='mode',
            field=models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references'), ('t2i', 'Image from text'), ('r2i', 'Provide references'), ('t2a', 'Audio from text'), ('r2a', 'Provide references')], max_length=8),
        ),
        migrations.AlterField(
            model_name='renderpreset',
            name='mode',
            field=models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references'), ('t2i', 'Image from text'), ('r2i', 'Provide references'), ('t2a', 'Audio from text'), ('r2a', 'Provide references')], max_length=8),
        ),
    ]
