# Generated by Django 6.0.8 on 2026-08-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0018_seed_image_audio_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='use_spectrum',
            field=models.BooleanField(default=False, help_text='Whether this job used the Spectrum step-forecasting accelerator (see extras.md) -- resolved from the request + settings.SPECTRUM_LEVEL at queue time (generation/api.py::_resolve_use_spectrum), not editable after. Does NOT adjust estimated_seconds above -- the real render is faster than that estimate when this is set (see extras.md).'),
        ),
    ]
