# Generated by Django 6.0.8 on 2026-08-08 14:17

import generation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0019_generationjob_use_spectrum'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='thumbnail_file',
            field=models.FileField(blank=True, upload_to=generation.models.generated_thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='title',
            field=models.CharField(blank=True, default='', help_text="User-editable label for this job in the queue/history (see generation/api.py's PATCH job_detail). Blank means the frontend falls back to showing (a truncated) raw_prompt instead -- see frontend/src/features/queue/jobTitle.ts.", max_length=200),
        ),
    ]
