# Generated by Django 6.0.8 on 2026-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0021_backfill_video_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text="Set by generation/api.py's cancel_job() on a PROCESSING job (the request that hits mid-render, as opposed to a still-QUEUED job, which is cancelled directly and synchronously instead). The actively-running tasks._execute_job() call for this job -- not the cancel request itself, to avoid a cross-process race overwriting whichever one saves status last -- polls this flag and, once ComfyUI's round trip ends one way or another, is what actually writes Status.CANCELLED."),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
