# Generated by Django 6.0.8 on 2026-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0022_generationjob_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='comfyui_output_filename',
            field=models.CharField(blank=True, default='', help_text="The rendered output's filename/subfolder on ComfyUI's own machine (see integrations/comfyui.py's ComfyUIOutput) -- distinct from video_file's own randomized storage name. Recorded for every job regardless of mode; only actually read back when keep_comfyui_output left the file in place for a following continuation Clip to reference (see integrations/motion_context.py).", max_length=255),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='comfyui_output_subfolder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='continuation_params',
            field=models.JSONField(blank=True, default=None, help_text="When set, build_api_workflow() splices in motion/audio continuity via integrations/motion_context.py::apply_motion_context(workflow, mode=job.mode, **continuation_params) -- see that function for the expected keys. Set by director/services.py; unused outside Director Mode. Mirrors use_spectrum's shape (a job-level flag/data driving an optional workflow splice) rather than introducing a separate extensibility mechanism.", null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='keep_comfyui_output',
            field=models.BooleanField(default=False, help_text="Skip tasks.py's usual delete_output_file() cleanup after downloading this job's result, leaving it in place on the ComfyUI machine. Set by director/services.py when creating a Clip's job, so a following continuation Clip's LoadVideo node can reference this job's output directly instead of Django downloading and re-uploading it (see integrations/motion_context.py). Unused outside Director Mode."),
        ),
    ]
