# Generated by Django 6.0.8 on 2026-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0023_generationjob_comfyui_output_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationjob',
            name='comfyui_output_filename',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='comfyui_output_subfolder',
        ),
        migrations.RemoveField(
            model_name='generationjob',
            name='keep_comfyui_output',
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='continuation_params',
            field=models.JSONField(blank=True, default=None, help_text="When set, build_api_workflow() splices in motion/audio continuity via integrations/motion_context.py::apply_motion_context(workflow, **continuation_params) -- see that function for the expected keys. Set by director/services.py; unused outside Director Mode. Mirrors use_spectrum's shape (a job-level flag/data driving an optional workflow splice) rather than introducing a separate extensibility mechanism.", null=True),
        ),
    ]
