# Generated by Django 6.0.8 on 2026-08-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0024_remove_generationjob_comfyui_output_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Hides this job from the default queue/history view without deleting it -- see generation/api.py's PATCH job_detail. The frontend filters this client-side (the list endpoint always returns every job, archived or not), same as its other queue filters."),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text="User-toggled 'hearted' flag for the queue/history list -- purely a display/filter aid (see generation/api.py's PATCH job_detail), no effect on rendering."),
        ),
    ]
