# Generated by Django 6.0.8 on 2026-08-10 16:26

import director.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0023_generationjob_comfyui_output_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('continues_previous', models.BooleanField(default=False, help_text="Splice motion/audio continuity from the immediately-preceding Clip's render. Only meaningful when mode is in CONTINUATION_CAPABLE_MODES and this isn't the project's first Clip -- enforced in the API layer, not here.")),
                ('mode', models.CharField(choices=[('t2v', 'Video from text'), ('i2v', 'Provide first frame'), ('r2v', 'Provide references'), ('t2i', 'Image from text'), ('r2i', 'Provide references'), ('t2a', 'Audio from text'), ('r2a', 'Provide references')], max_length=8)),
                ('prompt', models.TextField(blank=True, default='')),
                ('improved_prompt', models.TextField(blank=True, default='')),
                ('aspect_ratio', models.CharField(help_text="Same shape as GenerationJob.aspect_ratio. Locked to the predecessor's value when continues_previous -- context frames must match resolution.", max_length=10)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('needs_render', models.BooleanField(default=True, help_text="Dirty flag -- shown as the red border on the board. See services.py's mark_dirty_cascade()/mark_project_dirty() for the only places this is set True, and the job_finished signal receiver in signals.py for the only place it's set False.")),
                ('checkpoint_filename_prefix', models.CharField(blank=True, default='', help_text="Set once this Clip successfully renders -- the filename_prefix passed to MiniMaxH3MotionContextSaveLatent, consumed by the *next* continuation Clip's MiniMaxH3MotionContextLoadLatent. Lives entirely as ComfyUI-side state (a safetensors file on its own disk) -- this is just the string needed to find it again, never any latent bytes.", max_length=200)),
                ('checkpoint_clip_index', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_clip', to='generation.generationjob')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_clips', to='generation.renderduration')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director_clips', to='generation.renderpreset')),
                ('render_chain_target', models.ForeignKey(blank=True, help_text="Set on the *head* Clip of an in-flight chain-render request to the Clip the user actually asked to render -- signals.py's auto-advance walks forward creating each next continuation Clip's job as its predecessor finishes, until it reaches this target (or a gap/failure stops it). Null when idle.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='director.clip')),
            ],
            options={
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ClipReferenceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to=director.models.clip_reference_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='director.clip')),
            ],
            options={
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('overarching_prompt', models.TextField(blank=True, default='', help_text="Shared world/setting/character context prose, given to every Clip's render and to the LLM prompt-assist calls made against this project's clips (see integrations/llm.py's extra_context).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='clip',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='director.project'),
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to=director.models.project_resource_upload_path)),
                ('label', models.CharField(blank=True, default='', help_text='e.g. "Alice — character sheet". Blank falls back to the same "Picture N"/"Video N"/"Audio N" token convention as ReferenceAsset.label.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='director.project')),
            ],
            options={
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(fields=('project', 'order'), name='unique_project_clip_order'),
        ),
    ]
