# Generated by Django 6.0.8 on 2026-08-10 16:33

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        ('generation', '0023_generationjob_comfyui_output_filename_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clip',
            name='unique_project_clip_order',
        ),
        migrations.AddConstraint(
            model_name='clip',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('project', 'order'), name='unique_project_clip_order'),
        ),
    ]
