# Generated by Django 6.0.8 on 2026-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_remove_clip_unique_project_clip_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='checkpoint_clip_index',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='checkpoint_filename_prefix',
        ),
        migrations.AddField(
            model_name='clip',
            name='chain_run_name',
            field=models.CharField(blank=True, default='', help_text="Set once this Clip successfully renders with real continuity (extension available) -- the MiniMaxH3ChainPlan run_name its checkpoint was saved under (see integrations/motion_context.py). Blank if this Clip has never rendered, or last rendered via the last-frame fallback (extension unavailable) -- see director/services.py's _resolve_chain_params(). A *continuation* Clip only inherits real continuity from its predecessor when the predecessor has this set; otherwise it falls back too, and stays on the fallback until a fresh (non-continuation) Clip starts a new run. Shared by every Clip in the same contiguous run -- lives entirely as ComfyUI-side state (a run of checkpoint files on its own disk); this is just the string needed to find them again, never any latent bytes.", max_length=200),
        ),
        migrations.AddField(
            model_name='clip',
            name='chain_scene_number',
            field=models.PositiveIntegerField(blank=True, help_text="This Clip's 1-based position within chain_run_name's run (matches MiniMaxH3ChainLoopStart's start_clip/scene_range) -- 1 for a fresh run.", null=True),
        ),
    ]
