# Generated by Django 6.0.8 on 2026-08-10 22:08

import director.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_remove_clip_checkpoint_clip_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assembled_video_file',
            field=models.FileField(blank=True, help_text='Final concatenated export of every clip in order -- see integrations/assembly.py, set by POST .../assemble/. Overwritten (old file deleted) on each re-export; not auto-invalidated when a clip is edited/re-rendered afterward, so a stale export can persist until the user re-runs assemble.', upload_to=director.models.project_assembled_video_upload_path),
        ),
    ]
