# Generated by Django 6.0.8 on 2026-08-11 09:13

import django.db.models.deletion
from django.db import migrations, models


def backfill_project_settings(apps, schema_editor):
    """Aspect ratio and quality are moving from per-Clip to per-Project (see
    this migration's schema changes) -- seed each existing Project's new
    fields from its first Clip's old (per-clip) values, run before the old
    Clip.aspect_ratio column is dropped below so there's still something to
    read. A project with divergent per-clip aspect ratios/presets (unlikely
    in practice -- continues_previous already forced them to match, and
    this deployment has had very little real usage) just adopts its first
    Clip's values; later Clips are silently left as-is until the next
    render/edit recomputes them against the new project-wide setting (see
    director/services.py's recompute_project_resolutions(), not run here to
    keep this migration a pure data-shape move, not a render-affecting one).
    """
    Project = apps.get_model("director", "Project")
    for project in Project.objects.all():
        first_clip = project.clips.order_by("order").first()
        if first_clip is None:
            continue
        update_fields = []
        if first_clip.aspect_ratio:
            project.aspect_ratio = first_clip.aspect_ratio
            update_fields.append("aspect_ratio")
        if first_clip.preset_id is not None:
            project.quality_label = first_clip.preset.label
            update_fields.append("quality_label")
        if update_fields:
            project.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_project_assembled_video_file'),
        ('generation', '0024_remove_generationjob_comfyui_output_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aspect_ratio',
            field=models.CharField(default='16:9', help_text="Applies to every Clip in the project, not chosen per-clip -- MiniMax H3's continuity model requires consistent resolution across a chain, and this app treats aspect ratio as a project-wide decision (see generation.resolution for valid values). Changing this recomputes every Clip's width/height and marks the whole project dirty -- see director/services.py's recompute_project_resolutions().", max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_label',
            field=models.CharField(blank=True, default='', help_text="The shared RenderPreset.label every Clip's own (per-mode) preset is resolved from -- see director/services.py's resolve_preset_for_mode(). Same project-wide reasoning as aspect_ratio above: quality is a whole-project decision here, not a per-clip one.", max_length=60),
        ),
        migrations.RunPython(backfill_project_settings, noop_reverse),
        migrations.RemoveField(
            model_name='clip',
            name='aspect_ratio',
        ),
        migrations.AlterField(
            model_name='clip',
            name='preset',
            field=models.ForeignKey(help_text="Derived from the project's quality_label for this Clip's own mode -- see director/services.py's resolve_preset_for_mode(). Not independently chosen; a cached snapshot the same way GenerationJob.preset is, so later catalog edits don't retroactively change what's already shown.", on_delete=django.db.models.deletion.PROTECT, related_name='director_clips', to='generation.renderpreset'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='width',
            field=models.PositiveIntegerField(help_text="Computed from preset.megapixels + project.aspect_ratio, except while continues_previous, where it's locked to the immediate predecessor's own width -- see director/services.py's resolve_clip_width_height()."),
        ),
    ]
