# Generated by Django 6.0.8 on 2026-08-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0005_remove_clip_aspect_ratio_project_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='script_text',
            field=models.TextField(blank=True, default='', help_text="The script/idea text last submitted to 'Generate from script' (see director/api.py's apply_plan()) -- kept so the source material can be reviewed or reused later. Not itself used at render time."),
        ),
    ]
