# Generated by Django 6.0.8 on 2026-08-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0006_project_script_text'),
        ('generation', '0025_generationjob_is_archived_generationjob_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_project_tag', to='generation.generationjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='director.project')),
            ],
        ),
    ]
